version: '3.8'
services:
  web:
    container_name: web
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    working_dir: /etc/nginx
    links:
      - python
  python:
    container_name: python
    build: ./docker/python
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build: docker/mysql
    container_name: mysql
    ports:
      - 3307:3306
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=fbam
    healthcheck:
      test: "exit 0"

volumes:
  data-volume:
