# Generated by Django 2.2.13 on 2020-12-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceGame',
            fields=[
                ('date', models.DateTimeField()),
                ('nickname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('q1', models.PositiveSmallIntegerField()),
                ('q2', models.PositiveSmallIntegerField()),
                ('q3', models.PositiveSmallIntegerField()),
                ('q4', models.PositiveSmallIntegerField()),
                ('q5', models.PositiveSmallIntegerField()),
                ('q6', models.PositiveSmallIntegerField()),
                ('q7', models.PositiveSmallIntegerField()),
                ('q8', models.PositiveSmallIntegerField()),
                ('q9', models.PositiveSmallIntegerField()),
                ('q10', models.PositiveSmallIntegerField()),
                ('q11', models.PositiveSmallIntegerField()),
                ('q12', models.PositiveSmallIntegerField()),
                ('q13', models.PositiveSmallIntegerField()),
                ('q14', models.PositiveSmallIntegerField()),
                ('q15', models.PositiveSmallIntegerField()),
                ('q16', models.PositiveSmallIntegerField()),
                ('q17', models.PositiveSmallIntegerField()),
                ('q18', models.PositiveSmallIntegerField()),
                ('q19', models.PositiveSmallIntegerField()),
                ('q20', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
