# Generated by Django 2.2.13 on 2021-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nicknames',
            fields=[
                ('nickname_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('q1', models.PositiveSmallIntegerField()),
                ('q2', models.PositiveSmallIntegerField()),
                ('q3', models.PositiveSmallIntegerField()),
                ('q4', models.PositiveSmallIntegerField()),
                ('q5', models.PositiveSmallIntegerField()),
                ('q6', models.PositiveSmallIntegerField()),
                ('q7', models.PositiveSmallIntegerField()),
                ('q8', models.PositiveSmallIntegerField()),
                ('q9', models.PositiveSmallIntegerField()),
                ('q10', models.PositiveSmallIntegerField()),
                ('q11', models.PositiveSmallIntegerField()),
                ('q12', models.PositiveSmallIntegerField()),
                ('q13', models.PositiveSmallIntegerField()),
                ('q14', models.PositiveSmallIntegerField()),
                ('q15', models.PositiveSmallIntegerField()),
                ('q16', models.PositiveSmallIntegerField()),
                ('q17', models.PositiveSmallIntegerField()),
                ('q18', models.PositiveSmallIntegerField()),
                ('q19', models.PositiveSmallIntegerField()),
                ('q20', models.PositiveSmallIntegerField()),
                ('nickname_id', models.ForeignKey(on_delete=True, to='service_tastemeasure.Nicknames')),
            ],
        ),
    ]
