# Generated by Django 2.2.13 on 2021-01-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_tastemeasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicknames',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
